### ISSUE TITLE
meybe you can help me . how used curl call contract api?

### ISSUE THREAD

**Issue by PHPJourney** [bancorprotocol/contracts#143]
I am a php developer . but  i read all document. also not find about contract used method
do u know. what's question?

as JSON-RPC not support eth_contract api.

i don't know what i do.

who know the question solution.

**Comment by yudilevi** [comment]
I'm not sure I fully understand the question, but it seems like a generic solidity question - you might want to join the solidity gitter room and ask there.

**Comment by PHPJourney** [comment]
yet,i am in gitter room.
but no people online.

**Comment by yudilevi** [comment]
there are always people online, just need to have some patience :)

**Comment by PHPJourney** [comment]
Let me try.

**Comment by PHPJourney** [comment]
meybe the people don't understand i question

**Comment by yudilevi** [comment]
Are you sure you're asking in the right room -
https://gitter.im/ethereum/solidity ?

**Comment by PHPJourney** [comment]
I'm sure
this room

**Comment by PHPJourney** [comment]
oh. i comeing solidity-dev
