### ISSUE TITLE
Compile errors when I try to test bancor contract

### ISSUE THREAD

**Issue by weiweiylw** [bancorprotocol/contracts#185]
Hello,
I got a few warnings and SyntaxError when I try to run 'npm test'. 

Node v6.9.4
TestRPC v6.0.3 (ganache-core: 2.0.2)
Truffle v4.0.1 (core: 4.0.1)
Solidity v0.4.18 (solc-js)

Here are the logs:

Compilation warnings encountered:

### 1.Warning: No visibility specified. Defaulting to "public". 

```
/home/david/eth_project/bancor/solidity/contracts/Owned.sol:16:5: Warning: No visibility specified. Defaulting to "public".
    function Owned() {
    ^
Spanning multiple lines.
```

### 2.Warning: Function state mutability can be restricted to pure. 

```
/home/david/eth_project/bancor/solidity/contracts/BancorFormula.sol:297:5: Warning: Function state mutability can be restricted to pure
    function floorLog2(uint256 _n) internal constant returns (uint8) {
    ^
Spanning multiple lines.
```

### 3.SyntaxError: Unexpected token.

```
/home/david/eth_project/bancor/solidity/migrations/2_deploy_contracts.js:19
module.exports = async (deployer) => {
                       ^
SyntaxError: Unexpected token (
    at Object.exports.createScript (vm.js:47:10)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:202038:23
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
npm ERR! Test failed.  See above for more details.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

I'm a beginner and need some help to fix these problems. Thx!

**Comment by yudilevi** [comment]
Hi,

The 2 warnings are not critical, we'll fix them in future versions.

The reason for the last one might be an older version of nodejs - which version are you using?
The tests require node 7.6+.

**Comment by weiweiylw** [comment]
@yudilevi I updated my Node and it works, thanks!
