### ISSUE TITLE
How to habdle Bancor Protocol supported token on exchange

### ISSUE THREAD

**Issue by shogochiai** [bancorprotocol/contracts#189]
Guys, technical suggestion please. Which contact/function can I use for retrieving current price of my Bancor Protocol supported token?

The background of my question is the relation of Bancor Protocol supported token with exchanges. Usually token price might be defined by demand-supply of majority-volume exchange, but in terms of Bancor world, token has it's price on blockchain as state. And this value must be the master indicator of exchange price. If my assumption could be correct, Bancor Protocol must have "get current price" kinda contact on solidity code. And as far as I know, price is retuned only on buy/sell time calculation contact. Could you kindly give me ideas?

**Comment by yudilevi** [comment]
Hi,

It's pretty easy, you can just call getReturn on the BancorConverter contract.
Or getPurchaseReturn/getSaleReturn though getReturn will call the correct one for you.
