### ISSUE TITLE
[Metamask] Metamask failing

### ISSUE THREAD

**Issue by webcaetano** [bancorprotocol/contracts#195]
New version of metamask 4.1.2 are resulting in multiple fails between aprove and convert.
I'm not sure if is a bancor website problem, or is just metamask.

**Comment by yudilevi** [comment]
@webcaetano hey :)
Yeah, it seems like the new version broke our integration.
We're going to fix it asap.

Thanks!

**Comment by webcaetano** [comment]
@yudilevi It seems only Chrome. Firefox are fine.

**Comment by webcaetano** [comment]
Firefox update their version and also broke.

Related
https://support.bancor.network/hc/en-us/articles/360001679911--Oh-no-error-message-debug-option-1

https://support.bancor.network/hc/en-us/articles/360001660652--Oh-no-error-message-debug-option-2

**Comment by yudilevi** [comment]
Thanks - we're talking to metamask to get that issue resolved as soon as possible.

See the open issue here -
https://github.com/MetaMask/metamask-extension/issues/3425

Yudi
