### ISSUE TITLE
is it possible to dummy a bancor exchange without ICO?

### ISSUE THREAD

**Issue by githubcyc** [bancorprotocol/contracts#215]
i wonder that where i can see various of `constant reserve` (like ETH or ERC20 Tokens). 

what is the difference of coin exchange rate (price) between [Cryptocurrency Market Capitalizations | CoinMarketCap](https://coinmarketcap.com/) and [Bancor Network](https://www.bancor.network/discover)??? 

❤️ ⭐️  Thanks a lot.

**Comment by yudilevi** [comment]
Hi,

Bancor Network has its own on-chain rate for each token in the network and the smart contracts in the network can be queried for the rate.
CoinMarketCap on the other hand, shows an aggregation of all the different markets, including Bancor Network.

Does that answer your question?
