### ISSUE TITLE
Is master always up to date with the currently deployed contract on chain?

### ISSUE THREAD

**Issue by elie222** [bancorprotocol/contracts#216]
Is master up to date with this?
https://etherscan.io/address/0x3839416bd0095d97bE9b354cBfB0F6807d4d609E#code

**Comment by yudilevi** [comment]
Hi,

master is currently up to date and we tried to keep it that way but it's not 100% guaranteed as sometimes we make minor changes that don't require new deployments and also sometimes it takes a bit of time until we deploy the latest contracts to the blockchain as we also need our app to support all the latest features before deployment.
