### ISSUE TITLE
Discover Token Relays addresses

### ISSUE THREAD

**Issue by k06a** [bancorprotocol/contracts#229]
Is there any way to discover all Token Relays and Smart Tokens to compose `path`?

**Comment by yudilevi** [comment]
You mean all available options?
We don't have a discovery service for tokens in the network yet, though it's possible to use any smart token in the network as part of the path.
Note that token relays are smart tokens as well, but a path can also end with a standard ERC20 token.

**Comment by yudilevi** [comment]
I believe you can use the currencies API to get that info -
https://api.bancor.network/0.1/currencies

It's a paged request.

**Comment by k06a** [comment]
@yudilevi thanks! This is exactly what I need!
