### ISSUE TITLE
Missing some tokens in API

### ISSUE THREAD

**Issue by k06a** [bancorprotocol/contracts#239]
For example, can't find token BNB in any page of this API: https://api.bancor.network/0.1/currencies/

**Comment by k06a** [comment]
It seems pages contains currencies with same symbols, had a wrong loop over pages because of this.

**Comment by yudilevi** [comment]
Is this still an issue? If so, can you please provide an example?

**Comment by k06a** [comment]
@yudilevi no, thank you
