### ISSUE TITLE
Error while converting eth to erc20 using BancorNetwork contract

### ISSUE THREAD

**Issue by bugduino** [bancorprotocol/contracts#240]
Hi,
I'm trying to convert some ETH to XBP using the convert call function of the BancorNetwork contract at "0xF20b9e713A33F61fA38792d2aFaF1cD30339126A" but It always returns me an amount equal to 0.

I'm using web3 0.20.6 and trying to do the following (amount 0.003281014854 ETH):

     bancor = Bancor.at("0xf20b9e713a33f61fa38792d2afaf1cd30339126a")
     bancor.convert.call(["0xc0829421C1d260BD3cB3E0F06cfE2D52db2cE315", "0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c", "0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c", "0xb79c3a1a2d50cc99459f3a21d709bcec86656e97", "0x5102791ca02fc3595398400bfe0e33d7b6c82267"], 3281014854000000, 1).then(res => console.log(res.toNumber()))

Am I missing something?

the estimateGas call is always failing too with 

    Error: gas required exceeds allowance or always failing transaction

Should I add a value to the call given that I'm converting from ETH? If yes how?

**Comment by barakman** [comment]
@bugduino:
Side-note: You probably want to avoid `res.toNumber()`, since the value of `res` may well be higher than Javascript's `Number.MAX_SAFE_INTEGER` (2 ^ 53 - 1).

**Comment by bugduino** [comment]
You are right! but the problem persists. I'm wondering if is something related to the gas limit imposed by bancor to avoid front runners

**Comment by bugduino** [comment]
I managed to get it working using a lower gas price for the call (1 gwei) so it was failing due to the gas limit
