### ISSUE TITLE
Error invalid address when running acceptOwnership function of SmartToken.sol

### ISSUE THREAD

**Issue by tpmccallum** [bancorprotocol/contracts#242]
I am getting the following error when calling the acceptOwnership function of SmartToken.sol
```
> deployedContract.acceptOwnership();
Error: invalid address
    at web3-cmt.js:12250:13
    at web3-cmt.js:12080:18
    at web3-cmt.js:13332:28
    at map (<native code>)
    at web3-cmt.js:13331:12
    at web3-cmt.js:13357:18
    at web3-cmt.js:13382:23
    at web3-cmt.js:12448:16
    at apply (<native code>)
    at web3-cmt.js:12534:16
```
The error seems to be asking for an argument of address type.
If I provide one (the address that deployed the contract i.e. the value returned from deployedContract.owner()) I get the following error (which makes sense given that the abi and Solidity code are argument-less)
```
Error: Invalid number of arguments to Solidity function
```
What is the purpose of the acceptOwnership function and how should/could it be used?

Many thanks
Tim

**Comment by barakman** [comment]
@tpmccallum:

Have you tried passing `{from: addr}` instead of `addr`?

**Comment by tpmccallum** [comment]
Ah, very good. Thank you I will try now.

**Comment by tpmccallum** [comment]
Thank you @barakman 
The following worked
deployedContract.issue("0xf7fca0066bde97e5509591afc9f669991e03c25c",10000000000, {from:accountA});

**Comment by tpmccallum** [comment]
deployedContract.acceptOwnership({from:accountA});
^^ worked :-)
