### ISSUE TITLE
web3.toBigNumber() is not a function

### ISSUE THREAD

**Issue by andytudhope** [bancorprotocol/contracts#280]
Running the test script, i.e. using Ganache under the hood works well.

However, even after looking at #268 and changing the web3-utils version to either `1.0.0-beta37` or `1.0.0-beta41`, I still cannot get this test suite to pass when not using the script, but rather running `truffle develop` and then `truffle test` from within the `solidity` directory. When I do, I always get:

```
TypeError: web3.toBigNumber is not a function
    at contract (~/test/contracts/solidity/test/BancorFormula.js:14:28)
```

Why does `truffle develop` differ from `ganache`? I ask because I am trying to solve this issue currently: https://github.com/status-im/discover-dapps/issues/14

**Comment by barakman** [comment]
@andytudhope :

The test-suite executed via `truffle test` or via `npm test 1` relies on Truffle v4.1.14, which in turn relies on Web3 v0.18.4. For this version of Web3, [`toBigNumber`](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3tobignumber) is a valid function.

I'm not sure how else you are trying to run the tests, but the error which you describe implies that your setup uses Web3 v1.x instead, where this function has been replaces with [`utils.toBN`](https://web3js.readthedocs.io/en/1.0/web3-utils.html#tobn).

Be cautious - these two functions are different not only in name, but also in behavior (if I remember correctly, the former truncates non-integer values while the latter throws exception on such input).

Note that in either case, it has nothing to do with Ganache.

**Comment by andytudhope** [comment]
Yeah, sorry for the confusion, have figured it out and should be able to push a proper Embark test suite to the above repo shortly 👍

**Comment by andytudhope** [comment]
@barakman https://github.com/status-im/discover-dapps/commit/3609bf9d6ae23e1a284bb38a1e8e0f8016cc6a1c

So close! All I need now is to figure out how to handle decimals with a different BigNumber library 😓 Any helpful leads?

**Comment by barakman** [comment]
@andytudhope : 

In file `package.json`:
- Add `"bignumber.js": "^8.0.0"`  (under `devDependencies`)

In any test script that you need to update:
- Add `const BigNumber = require("bignumber.js");`
- Replace `web3.toBigNumber` with `new BigNumber`

See [here](http://mikemcl.github.io/decimal.js/) for the official documentation of this module.

**Comment by andytudhope** [comment]
@barakman yeah, that's what that commit above does, it's the decimals I am struggling with now: https://github.com/status-im/discover-dapps/blob/develop/test/BancorFormula_spec.js#L203

(The `Math.floor()` shouldn't be there, was just trying some random stuff... If you uncomment that block, you get

```
AssertionError [ERR_ASSERTION]: Error: [number-to-bn] while converting number "4.5956818223498375920701783577961055462157623760458422993543318099514112549881422701542626479610988660428118371519990977285977858991135391744e+38" to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported. Given value: "4.5956818223498375920701783577961055462157623760458422993543318099514112549881422701542626479610988660428118371519990977285977858991135391744e+38"
```

**Comment by barakman** [comment]
@andytudhope : 
Just replace `func(x)` with `func(x.truncated())` for any `func` which takes a `BigNumber` input.

**Comment by andytudhope** [comment]
Yeah, I know, but `x.truncated()` is not a function in that `bignumber.js` library unfortunately.

Thanks for the tip on `new`, will update.

My issue is 2-fold:

1. `truncate()` is not a function. I can use `toFormat()` which should be the same, but doesn't appear to be functioning as such.
2. I'm having to `web3.utils.toHex()` all the bignumbers before passing them as args to the contract call because Embark doesn't like that.

Somewhere between removing truncate and toHex, things go wrong and I can't get the last chunk of tests to pass: https://github.com/status-im/discover-dapps/blob/develop/test/BancorFormula_spec.js#L201

BTW, I should just say that this test suite is an inspiration and you, @barakman, are a wizard :heart:

**Comment by barakman** [comment]
@andytudhope : 
Thank you!!!

What `BigNumber` version are you using?

You can get it by entering the command-line `npm ls bignumber`.

**Comment by andytudhope** [comment]
`bignumber.js@8.1.1`

**Comment by barakman** [comment]
@andytudhope : 
Then you can use `integerValue` instead of `truncated`.

You might find [the official documentation](https://mikemcl.github.io/bignumber.js/) quite useful.
