### ISSUE TITLE
MAX_GAS_PRICE Degrades Ecosystem UX and Helps Whales

### ISSUE THREAD

**Issue by naterush** [bancorprotocol/contracts#9]
Adding an MAX_GAS_PRICE will likely cause miners to modify software to accept bribes using smart contracts like this: https://gist.github.com/naterush/ab172a26946ada6712db2e76c64b11a8

This is such a simple change/workaround (for such a high reward; see gas profits off recent ICOs) all rational miners will likely accept this very soon if there are contracts that enforce a MAX_GAS_PRICE.

Encouraging miners to accept bribes is bad for a couple reasons. 
1. Out of band payments are much less visible. This would mean that it’s would be significantly more complicated to choose a reasonable gas price for a transaction. 
2. Out of band payment would likely favor technical users more than regular users (takes effort/knowledge to do).

Both of these things would lead to worse average user experience - and would likely favor whales more than it hurts them.

If this is the case, Bancor has the duty to not impose a MAX_GAS_LIMIT, as it will likely lead to bribing channels in the very near future. This is a short-term "fix" for a single ICO that is meant to stop whales, but actually, may lead to negative outcomes for most users and be positive for whales.

**Comment by yudilevi** [comment]
You're correct - this method should not be implemented as a long term solution.
It worked great for us (and maybe will work well for another few weeks) but that's it - I do not encourage using it in a long term solution/contract as - just as you mentioned - will be bypassed eventually and create the opposite effect.
